title: SLF4M
email: andrew@apjanke.net
description: Simple, powerful logging for Matlab

baseurl: "/"
url: ""

theme: jekyll-theme-cayman

github_username: janklab
google_analytics: G-B6G2FLSWGL

# Fixed GitHub Pages configuration
markdown: kramdown
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - Gemfile*

keep_files:
  - images

plugins:
  # Forced by GitHub Pages
  - jekyll-asciidoc
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings
  # Supported by GitHub Pages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
